# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 475)
        Form.setMinimumSize(QtCore.QSize(401, 475))
        Form.setMaximumSize(QtCore.QSize(401, 475))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/img/AppLogo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.header = QtWidgets.QFrame(parent=Form)
        self.header.setGeometry(QtCore.QRect(0, 0, 401, 42))
        self.header.setStyleSheet("#header{\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(59, 59, 59, 255), stop:1 rgba(49, 49, 49, 255));\n"
"    border-top-right-radius: 12px;\n"
"    border-top-left-radius: 12px;\n"
"}\n"
"\n"
".QToolButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
".QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: white\n"
"}\n"
"\n"
".QToolButton:hover{\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header.setObjectName("header")
        self.Title = QtWidgets.QLabel(parent=self.header)
        self.Title.setGeometry(QtCore.QRect(90, 9, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color: rgb(255, 255, 255);")
        self.Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Title.setObjectName("Title")
        self.CloseButton = QtWidgets.QToolButton(parent=self.header)
        self.CloseButton.setGeometry(QtCore.QRect(364, 6, 30, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/img/iconamoon_close-light.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.CloseButton.setIcon(icon1)
        self.CloseButton.setIconSize(QtCore.QSize(24, 24))
        self.CloseButton.setObjectName("CloseButton")
        self.HideButton = QtWidgets.QToolButton(parent=self.header)
        self.HideButton.setGeometry(QtCore.QRect(330, 6, 30, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/img/mynaui_minus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.HideButton.setIcon(icon2)
        self.HideButton.setIconSize(QtCore.QSize(24, 24))
        self.HideButton.setObjectName("HideButton")
        self.Icon = QtWidgets.QLabel(parent=self.header)
        self.Icon.setGeometry(QtCore.QRect(9, 9, 24, 24))
        self.Icon.setText("")
        self.Icon.setPixmap(QtGui.QPixmap("res/img/Vector.png"))
        self.Icon.setObjectName("Icon")
        self.content = QtWidgets.QFrame(parent=Form)
        self.content.setGeometry(QtCore.QRect(0, 42, 401, 433))
        self.content.setStyleSheet("#content{\n"
"background-color: rgb(59, 59, 59);\n"
"border-bottom-left-radius: 12px;\n"
"border-bottom-right-radius: 12px;\n"
"}\n"
"\n"
".QLineEdit{\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(59, 59, 59, 255), stop:1 rgba(49, 49, 49, 255));\n"
"    border-radius: 7px;\n"
"    border: 1px solid rgba(255, 255, 255, 20);\n"
"    color: white\n"
"}\n"
"\n"
".QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(235, 46, 65, 255), stop:1 rgba(208, 0, 76, 255));\n"
"    border-radius: 12px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
".QPushButton:hover{\n"
"background-color: rgb(172, 22, 59);\n"
"}")
        self.content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content.setObjectName("content")
        self.Title_2 = QtWidgets.QLabel(parent=self.content)
        self.Title_2.setGeometry(QtCore.QRect(20, 42, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Medium")
        font.setPointSize(21)
        self.Title_2.setFont(font)
        self.Title_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.Title_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Title_2.setWordWrap(True)
        self.Title_2.setObjectName("Title_2")
        self.Title_3 = QtWidgets.QLabel(parent=self.content)
        self.Title_3.setGeometry(QtCore.QRect(20, 80, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.Title_3.setFont(font)
        self.Title_3.setStyleSheet("color: rgba(255, 255, 255, 127);")
        self.Title_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.Title_3.setWordWrap(True)
        self.Title_3.setObjectName("Title_3")
        self.LoginLine = QtWidgets.QLineEdit(parent=self.content)
        self.LoginLine.setGeometry(QtCore.QRect(20, 140, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Medium")
        font.setPointSize(10)
        self.LoginLine.setFont(font)
        self.LoginLine.setStyleSheet("padding-left: 7px;")
        self.LoginLine.setInputMask("")
        self.LoginLine.setText("")
        self.LoginLine.setMaxLength(15)
        self.LoginLine.setObjectName("LoginLine")
        self.PasswordLine = QtWidgets.QLineEdit(parent=self.content)
        self.PasswordLine.setGeometry(QtCore.QRect(20, 190, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Medium")
        font.setPointSize(10)
        self.PasswordLine.setFont(font)
        self.PasswordLine.setStyleSheet("padding-left: 7px;")
        self.PasswordLine.setInputMask("")
        self.PasswordLine.setText("")
        self.PasswordLine.setMaxLength(15)
        self.PasswordLine.setObjectName("PasswordLine")
        self.LoginButton = QtWidgets.QPushButton(parent=self.content)
        self.LoginButton.setGeometry(QtCore.QRect(20, 290, 361, 49))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoginButton.sizePolicy().hasHeightForWidth())
        self.LoginButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Medium")
        font.setPointSize(12)
        self.LoginButton.setFont(font)
        self.LoginButton.setObjectName("LoginButton")
        self.RegistartionButton = QtWidgets.QPushButton(parent=self.content)
        self.RegistartionButton.setGeometry(QtCore.QRect(20, 350, 361, 49))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RegistartionButton.sizePolicy().hasHeightForWidth())
        self.RegistartionButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Medium")
        font.setPointSize(12)
        self.RegistartionButton.setFont(font)
        self.RegistartionButton.setStyleSheet(".QPushButton{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
".QPushButton:hover{\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.RegistartionButton.setObjectName("RegistartionButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Авторизация"))
        self.Title.setText(_translate("Form", "Авторизация"))
        self.CloseButton.setText(_translate("Form", "..."))
        self.HideButton.setText(_translate("Form", "..."))
        self.Title_2.setText(_translate("Form", "Авторизация"))
        self.Title_3.setText(_translate("Form", "Если у вас еще нет аккаунта, нажмите на кнопку регистрации."))
        self.LoginLine.setPlaceholderText(_translate("Form", "Логин"))
        self.PasswordLine.setPlaceholderText(_translate("Form", "Пароль"))
        self.LoginButton.setText(_translate("Form", "Авторизоваться"))
        self.RegistartionButton.setText(_translate("Form", "Регистрация"))
