# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(933, 549)
        Form.setMinimumSize(QtCore.QSize(933, 549))
        Form.setMaximumSize(QtCore.QSize(933, 549))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/img/AppLogo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.header = QtWidgets.QFrame(parent=Form)
        self.header.setGeometry(QtCore.QRect(0, 0, 933, 85))
        self.header.setStyleSheet("#header{\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(59, 59, 59, 255), stop:1 rgba(49, 49, 49, 255));\n"
"border-top-right-radius: 12px;\n"
"border-top-left-radius: 12px;\n"
"}\n"
"\n"
".QToolButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
".QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-radius: 5px;\n"
"    color: white\n"
"}\n"
"\n"
".QPushButton:hover{\n"
"background-color: rgba(0, 0, 0, 50);\n"
"}\n"
"\n"
".QToolButton:hover{\n"
"background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header.setObjectName("header")
        self.Title = QtWidgets.QLabel(parent=self.header)
        self.Title.setGeometry(QtCore.QRect(380, 13, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color: rgb(255, 255, 255);")
        self.Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Title.setObjectName("Title")
        self.CloseButton = QtWidgets.QToolButton(parent=self.header)
        self.CloseButton.setGeometry(QtCore.QRect(897, 6, 30, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/img/iconamoon_close-light.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.CloseButton.setIcon(icon1)
        self.CloseButton.setIconSize(QtCore.QSize(24, 24))
        self.CloseButton.setObjectName("CloseButton")
        self.HideButton = QtWidgets.QToolButton(parent=self.header)
        self.HideButton.setGeometry(QtCore.QRect(865, 6, 30, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/img/mynaui_minus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.HideButton.setIcon(icon2)
        self.HideButton.setIconSize(QtCore.QSize(24, 24))
        self.HideButton.setObjectName("HideButton")
        self.Icon = QtWidgets.QLabel(parent=self.header)
        self.Icon.setGeometry(QtCore.QRect(9, 9, 24, 24))
        self.Icon.setText("")
        self.Icon.setPixmap(QtGui.QPixmap("res/img/Vector.png"))
        self.Icon.setObjectName("Icon")
        self.LoginButon = QtWidgets.QPushButton(parent=self.header)
        self.LoginButon.setGeometry(QtCore.QRect(760, 40, 161, 36))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.LoginButon.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/img/qlementine-icons_user-16.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.LoginButon.setIcon(icon3)
        self.LoginButon.setIconSize(QtCore.QSize(24, 24))
        self.LoginButon.setObjectName("LoginButon")
        self.PremiumButton = QtWidgets.QPushButton(parent=self.header)
        self.PremiumButton.setGeometry(QtCore.QRect(570, 40, 181, 36))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.PremiumButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res/img/fluent_premium-24-filled.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PremiumButton.setIcon(icon4)
        self.PremiumButton.setIconSize(QtCore.QSize(24, 24))
        self.PremiumButton.setObjectName("PremiumButton")
        self.content = QtWidgets.QFrame(parent=Form)
        self.content.setGeometry(QtCore.QRect(0, 85, 933, 464))
        self.content.setStyleSheet("#content{\n"
"background-color: rgb(59, 59, 59);\n"
"border-bottom-left-radius: 12px;\n"
"border-bottom-right-radius: 12px;\n"
"}")
        self.content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content.setObjectName("content")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.content)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 911, 441))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SoloLoad = QtWidgets.QToolButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SoloLoad.sizePolicy().hasHeightForWidth())
        self.SoloLoad.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.SoloLoad.setFont(font)
        self.SoloLoad.setStyleSheet(".QToolButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(59, 59, 59,         255), stop:1 rgba(49, 49, 49, 255));\n"
"    border-radius: 12px;\n"
"    border: 1px solid rgba(255, 255, 255, 20);\n"
"    color: white;\n"
"}\n"
"\n"
".QToolButton:hover{\n"
"    background-color: #2F2F2F;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("res/img/iconamoon_file-light.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.SoloLoad.setIcon(icon5)
        self.SoloLoad.setIconSize(QtCore.QSize(64, 64))
        self.SoloLoad.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.SoloLoad.setObjectName("SoloLoad")
        self.verticalLayout.addWidget(self.SoloLoad)
        self.MultiLoad = QtWidgets.QToolButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MultiLoad.sizePolicy().hasHeightForWidth())
        self.MultiLoad.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.MultiLoad.setFont(font)
        self.MultiLoad.setStyleSheet(".QToolButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(59, 59, 59, 255), stop:1 rgba(49, 49, 49, 255));\n"
"    border-radius: 12px;\n"
"    border: 1px solid rgba(255, 255, 255, 20);\n"
"    color: white;\n"
"}\n"
"\n"
".QToolButton:hover{\n"
"    background-color: #2F2F2F;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("res/img/system-uicons_files-multi.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.MultiLoad.setIcon(icon6)
        self.MultiLoad.setIconSize(QtCore.QSize(64, 64))
        self.MultiLoad.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.MultiLoad.setObjectName("MultiLoad")
        self.verticalLayout.addWidget(self.MultiLoad)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "VideoConverter"))
        self.Title.setText(_translate("Form", "VideoConverter"))
        self.CloseButton.setText(_translate("Form", "..."))
        self.HideButton.setText(_translate("Form", "..."))
        self.LoginButon.setText(_translate("Form", "Войти в аккаунт"))
        self.PremiumButton.setText(_translate("Form", "Премиум-функции"))
        self.SoloLoad.setText(_translate("Form", "Конвертировать видео"))
        self.MultiLoad.setText(_translate("Form", "Конвертировать несколько видео"))
